export const ADD_VOCAB_BEGINS = 'ADD_VOCAB_BEGINS';
export const ADD_VOCAB_SUCCESS = 'ADD_VOCAB_SUCCESS';
export const ADD_VOCAB_FAILURE = 'ADD_VOCAB_FAILURE';

export const GET_VOCAB_BEGINS = 'GET_VOCAB_BEGINS';
export const GET_VOCAB_SUCCESS = 'GET_VOCAB_SUCCESS';
export const GET_VOCAB_FAILURE = 'GET_VOCAB_FAILURE';

export const UPDATE_VOCAB_BEGINS = 'UPDATE_VOCAB_BEGINS';
export const UPDATE_VOCAB_SUCCESS = 'UPDATE_VOCAB_SUCCESS';
export const UPDATE_VOCAB_FAILURE = 'UPDATE_VOCAB_FAILURE';

export const DELETE_VOCAB_BEGINS = 'DELETE_VOCAB_BEGINS';
export const DELETE_VOCAB_SUCCESS = 'DELETE_VOCAB_SUCCESS';
export const DELETE_VOCAB_FAILURE = 'DELETE_VOCAB_FAILURE';
